koha:
  base_url: http://host:port/path
  base_url: http://host:port/path
  password: user
  user: password
  svc_check: /path/to/script
  svc_create: /path/to/script
  svc_update: /path/to/script
mq:
  rest_url: http://host/path-to-python-mq
  rest_api_key: othersecretkey 
api_key: verysecretkey
