koha:
  base_url:     <%= ENV["KOHA_BASE_URL"  ] %>
  user:         <%= ENV["KOHA_USER"      ] %>
  password:     <%= ENV["KOHA_PASS"      ] %>
  svc_check:    <%= ENV["KOHA_SVC_CHECK" ] %>
  svc_create:   <%= ENV["KOHA_SVC_CREATE"] %>
  svc_update:   <%= ENV["KOHA_SVC_UPDATE"] %>
mq:
  rest_url:     <%= ENV["MQ_REST_URL"    ] %>
  rest_api_key: <%= ENV["MQ_REST_API_KEY"] %>

