koha:
  base_url: http://host:port/path
  base_url: http://host:port/path
  password: user
  user: password
  svc_check: /path/to/script
  svc_create: /path/to/script
  svc_update: /path/to/script
api_key: verysecretkey
