default: &default
  adapter:   postgresql
  encoding:  unicode
  collation: sv_SE.UTF-8
  ctype:     sv_SE.UTF-8
  pool:      5
  timeout:   5000
  template:  template0
  host:      <%= ENV["DB_HOST"] %>
  port:      <%= ENV["DB_PORT"] %>
  database:  <%= ENV["DB_NAME"] %>
  username:  <%= ENV["DB_USER"] %>
  password:  <%= ENV["DB_PASS"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default

lab:
  <<: *default
